### PR TITLE
Use fallback for optional when decoding explicit nulls

### PR DESCRIPTION
**Pull request by freakingawesome**
Created in response to http://stackoverflow.com/questions/38461472/expecting-something-custom-error

### CODE REVIEW

**Comment by jamesmacaulay** [comment]
This change would be good for apps that don't care about the difference between `null` and a missing property, but could be bad for apps that do care about that distinction.

Apps that do care about the distinction may be relying on the current behavior and could be broken by this change, especially since the type of `optional` remains the same so it would be easy for users of the library not to notice the change.

If this is merged, then I'd suggest a major version bump, along with a clear warning in the release notes.

**Comment by rtfeldman** [comment]
Definitely would be a breaking change, so a major version bump seems wise. 😄

**Comment by lukewestby** [comment]
If you did care about it and wanted to decode as a maybe it wouldn't be so bad to do

``` elm
|> optional "something" (map Just int) Nothing
```

or use a `nullOr` higher-order decoder with `required`

LGTM!

**Comment by rtfeldman** [comment]
Okay, doing it!

**Comment by rtfeldman** [comment]
Thanks @freakingawesome!

**Comment by rtfeldman** [comment]
Released as 2.0.0! Thanks @freakingawesome @jamesmacaulay

**Pull request merged**
